language: php

php:
  - 8.0
  - 7.4

matrix:
  include:
    - php: 7.4
      dist: precise

before_script:
  - apt update
  - apt install -y git wget unzip
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - php ./vendor/bin/phpunit
