name: Integration

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: PHP Composer
        uses: php-actions/composer@v5

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php_version: 7.4
